<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>kasthack.telemetry.dbconnection.di</PackageId>
    <Description>IServiceCollection extensions for kasthack.telemetry.dbconnection with IOptions support.</Description>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.CLSCompliantAttribute">
      <_Parameter1>true</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\kasthack.telemetry.dbconnection\kasthack.telemetry.dbconnection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
